/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.applikasipemantaugizi06;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Halamanutama1 extends javax.swing.JFrame {

    /**
     * Creates new form Halamanutama
     */
    public Halamanutama1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Halamanutama = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tb = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        pria = new javax.swing.JButton();
        wanitaa = new javax.swing.JButton();
        RS = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Halamanutama.setBackground(new java.awt.Color(255, 153, 51));

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));

        jLabel2.setText("Nama :");

        jLabel3.setText("Gender :");

        jLabel4.setText("Usia :");

        jLabel5.setText("Berat Badan :");

        jLabel6.setText("Tinggi Badan :");

        ok.setText("Hitung");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        pria.setText("Pria");
        pria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priaActionPerformed(evt);
            }
        });

        wanitaa.setText("Wanita");
        wanitaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wanitaaActionPerformed(evt);
            }
        });

        RS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jakarta", "Bandung", "Surabaya", "Semarang", "Yogjakarta", "Malang", "Surakarta", "Cirebon", "Bogor", "Medan", "Palembang", "Padang", "Pekanbaru", "Bandar Lampung", "Banda Aceh" }));
        RS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RSActionPerformed(evt);
            }
        });

        jLabel7.setText("Daftar rumah sakit yang ada di kota anda");

        jButton3.setText("Lihat berita");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RS, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jButton3))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ok)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pria)
                                .addGap(18, 18, 18)
                                .addComponent(wanitaa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(usia, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bb, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pria)
                    .addComponent(wanitaa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(usia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(bb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ok)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        hasil.setColumns(20);
        hasil.setRows(5);
        hasil.setText("Hasil:");
        jScrollPane1.setViewportView(hasil);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        jLabel1.setText("Menu Utama");

        jButton1.setText("Lihat Detail");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Keluar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HalamanutamaLayout = new javax.swing.GroupLayout(Halamanutama);
        Halamanutama.setLayout(HalamanutamaLayout);
        HalamanutamaLayout.setHorizontalGroup(
            HalamanutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanutamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HalamanutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HalamanutamaLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HalamanutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addGroup(HalamanutamaLayout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))))
                    .addGroup(HalamanutamaLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        HalamanutamaLayout.setVerticalGroup(
            HalamanutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HalamanutamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HalamanutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HalamanutamaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HalamanutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Halamanutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Halamanutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
double TINGGI;
double BERAT;
double USIA;
double Tinggi;
double bmi;
double Kebutuhanprotein;
double kebutuhankaloriharian;
String kebutuhankaloriharianstring;
String Kebutuhanproteinstring;
String hasilhasil;
String info;
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        TINGGI = Double.parseDouble(tb.getText());
        BERAT = Double.parseDouble(bb.getText());
        USIA = Double.parseDouble(usia.getText());
        Tinggi = (TINGGI+TINGGI)/100;
        bmi = BERAT / Tinggi ;
        hasilhasil = Double.toString(bmi);
        Kebutuhanprotein = BERAT*8/10;
        kebutuhankaloriharian = 66 + (13.7*BERAT) + (5*TINGGI) - (6.8*USIA);
        kebutuhankaloriharianstring = Double.toString(kebutuhankaloriharian);
        Kebutuhanproteinstring = Double.toString(Kebutuhanprotein);
        if (bmi < 18){
            info = "Berat badan anda belum ideal, kekurangan berat badan";
    }   else if ((bmi > 18)&&(bmi < 22)){
            info = "Berat badan anda sudah ideal";
    }   else if ((bmi > 22)){
            info = "Berat badan anda belum ideal, kelebihan berat badan";
    }
        hasil.setText("Hasil :" + "\n" + "Nama : " + (nama.getText()) + "\n" + "Gender :" + Gender + "\n" + "Usia :" + (usia.getText()) + "\n" + "Berat Badan :" + (bb.getText()) + "\n" + "Tinggi badan :" + (tb.getText())+ "\n" + "Body Mass Index (BMI) :" + hasilhasil + "\n" + "Kebutuhan Protein :" + Kebutuhanproteinstring +  "\n" + "Kebutuhan Kalori harian :" + kebutuhankaloriharianstring +  "\n" + info); 
    }//GEN-LAST:event_okActionPerformed
String Gender;
    private void wanitaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wanitaaActionPerformed
        // TODO add your handling code here:
        Gender = "Wanita";
    }//GEN-LAST:event_wanitaaActionPerformed

    private void priaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priaActionPerformed
        // TODO add your handling code here:
        Gender = "Pria";
    }//GEN-LAST:event_priaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Halamanutama.removeAll();
        Halamanutama.repaint();
        Halamanutama.revalidate();
        Halamanutama.add(hasil);
        Halamanutama.repaint();
        Halamanutama.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "apakah anda yakin ingin keluar?");
        this.setVisible(false);
        if (dialogResult == 0) {
            Login n = new Login();
            n.setVisible(true);
        } else {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void RSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RSActionPerformed
        // TODO add your handling code here:
        switch(RS.getSelectedIndex()){
            case 0:
            hasil.setText("RSUPN Dr. Cipto Mangunkusumo" + "\n" + "Alamat: Jl. Diponegoro No.71, Kenari, Senen, Jakarta Pusat" + "\n" + "RS Pondok Indah" + "\n" + "Alamat: Jl. Metro Duta Kav UE, Pondok Indah, Jakarta Selatan");
            break;
            case 1:
            hasil.setText("RS Hasan Sadikin" + "\n" + "Alamat: Jl. Pasteur No.38, Sukajadi, Bandung" + "\n" + "RS Santosa" + "\n" + "Alamat: Jl. Kebonjati No.38, Kebon Jeruk, Andir, Bandung");
            break;
            case 2:
            hasil.setText("RSUD Dr. Soetomo" + "\n" + "Alamat: Jl. Mayjen Prof. Dr. Moestopo No.6-8, Airlangga, Gubeng, Surabaya" + "\n" + "RS Mitra Keluarga" + "\n" + "Alamat: Jl. Satelit Indah I, Tanjungsari, Sukomanunggal, Surabaya");
            break;
            case 3:
            hasil.setText("RSUP Dr. Kariadi" + "\n" + "Alamat: Jl. Dr. Sutomo No.16, Randusari, Semarang Selatan, Semarang" + "\n" + "RS Telogorejo" + "\n" + "Alamat: Jl. KH. Ahmad Dahlan No.1, Pekunden, Semarang Tengah, Semarang");
            break;
            case 4:
            hasil.setText("RSUP Dr. Sardjito" + "\n" + "Alamat: Jl. Kesehatan No.1, Senolowo, Sinduadi, Mlati, Sleman" + "\n" + "RS Panti Rapih" + "\n" + "Alamat: Jl. Cik Di Tiro No.30, Terban, Gondokusuman, Yogyakarta" );
            break;
            case 5:
            hasil.setText("RS Saiful Anwar\n" + "Alamat: Jl. Jaksa Agung Suprapto No.2, Klojen, Malang" + "RS Panti Nirmala\n" + "Alamat: Jl. Kebalen Wetan No.1, Kotalama, Kedungkandang, Malang");
            break;
            case 6:
            hasil.setText("RS Dr. Moewardi\n" + "Alamat: Jl. Kolonel Sutarto No.132, Jebres, Surakarta\n" + "RS Kasih Ibu\n" + "Alamat: Jl. Slamet Riyadi No.404, Pajang, Laweyan, Surakarta");
            break;
            case 7:
            hasil.setText("RS Gunung Jati\n" + "Alamat: Jl. Kesambi Raya No.56, Drajat, Kesambi, Cirebon\n" + "RS Sumber Kasih\n" + "Alamat: Jl. Siliwangi No.135, Kejaksan, Cirebon");
            break;
            case 8:
            hasil.setText("RS PMI Bogor\n" + "Alamat: Jl. Raya Pajajaran No.80, Baranangsiang, Bogor Timur, Bogor\n" + "RS Azra\n" + "Alamat: Jl. Raya Pajajaran No.219, Bantarjati, Bogor Utara, Bogor");
            break;
        }
    }//GEN-LAST:event_RSActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        hasil.setText("Berita terbaru tentang gizi di Indonesia menunjukkan beberapa perkembangan penting dalam upaya\n" +
"mengatasi masalah gizi buruk, khususnya stunting. Menurut hasil Survei Status Gizi Indonesia (SSGI)\n" +
"tahun 2022, prevalensi stunting di Indonesia turun dari 24,4% pada tahun 2021 menjadi 21,6% pada\n" +
"tahun 2022​ (UPK Kemkes)​​ (Kemkes)​. Penurunan ini sejalan dengan target yang dicanangkan oleh\n" +
"Kementerian Kesehatan, yaitu menurunkan angka stunting hingga 14% pada tahun 2024.");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halamanutama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halamanutama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halamanutama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halamanutama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Halamanutama1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Halamanutama;
    private javax.swing.JComboBox<String> RS;
    private javax.swing.JTextField bb;
    private javax.swing.JTextArea hasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama;
    private javax.swing.JButton ok;
    private javax.swing.JButton pria;
    private javax.swing.JTextField tb;
    private javax.swing.JTextField usia;
    private javax.swing.JButton wanitaa;
    // End of variables declaration//GEN-END:variables
}
